services:
  - type: web
    name: bookshelf
    runtime: node
    rootDir: .
    buildCommand: npm install && cd client && npm install && cd .. && npx prisma generate && npx prisma migrate deploy && npm run client:build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prod.db
      - key: GOOGLE_BOOKS_API_KEY
        sync: false
    autoDeploy: true
    plan: free